version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(actions)"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(python)"
    groups:
      python-patch-minor:
        update-types:
          - patch
          - minor

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Berlin
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - security
    commit-message:
      prefix: "deps(docker)"
