from __future__ import annotations

from collections.abc import Mapping
from uuid import UUID
from velvet_bot.application.media_delivery import MediaDeliveryJob, MediaDeliveryStatus, MediaDeliveryStepStatus
from velvet_bot.application.media_tasks import task_payload_mapping, task_result_urls
from velvet_bot.database import Database
from velvet_bot.infrastructure.media_delivery_repository_helpers import _TERMINAL_STATUSES, _VIDEO_MODELS, _error_text, _job_from_rows, _json, _text, delivery_metadata, first_text, media_kind, optional_int

class MediaDeliveryRepositoryRecordMixin:

    def __init__(self, database: Database) -> None:
        self._database = database

    async def record_provider_submission(self, *, task_id: UUID, provider: str, provider_task_id: str, chat_id: int | None, media_kind: str, request: Mapping[str, object]) -> None:
        async with self._database.acquire() as connection:
            await connection.execute("\n                INSERT INTO media_delivery_jobs (\n                    task_id, provider, provider_task_id, chat_id, media_kind,\n                    request_metadata, status, provider_submitted_at,\n                    next_attempt_at, created_at, updated_at\n                ) VALUES (\n                    $1::UUID, $2::VARCHAR, $3::TEXT, $4::BIGINT, $5::VARCHAR,\n                    $6::JSONB, 'provider_submitted', NOW(), NOW(), NOW(), NOW()\n                )\n                ON CONFLICT (task_id) DO UPDATE\n                SET provider = EXCLUDED.provider,\n                    provider_task_id = EXCLUDED.provider_task_id,\n                    chat_id = COALESCE(EXCLUDED.chat_id, media_delivery_jobs.chat_id),\n                    media_kind = EXCLUDED.media_kind,\n                    request_metadata = EXCLUDED.request_metadata,\n                    status = CASE\n                        WHEN media_delivery_jobs.status IN ('delivered', 'partial')\n                            THEN media_delivery_jobs.status\n                        ELSE 'provider_submitted'\n                    END,\n                    provider_submitted_at = COALESCE(\n                        media_delivery_jobs.provider_submitted_at,\n                        NOW()\n                    ),\n                    updated_at = NOW()\n                ", task_id, _text(provider, 'unknown')[:32], _text(provider_task_id, str(task_id)), chat_id, media_kind(media_kind), _json(request))

    async def record_provider_success(self, *, task_id: UUID, provider: str, provider_task_id: str, chat_id: int | None, media_kind: str, request: Mapping[str, object], result_urls: tuple[str, ...]) -> None:
        urls = tuple((url for value in result_urls if (url := str(value or '').strip())))
        async with self._database.acquire() as connection:
            async with connection.transaction():
                await connection.execute("\n                    INSERT INTO media_delivery_jobs (\n                        task_id, provider, provider_task_id, chat_id, media_kind,\n                        request_metadata, status, provider_submitted_at,\n                        provider_success_at, result_resolved_at, next_attempt_at,\n                        created_at, updated_at\n                    ) VALUES (\n                        $1::UUID, $2::VARCHAR, $3::TEXT, $4::BIGINT, $5::VARCHAR,\n                        $6::JSONB, 'provider_success', NOW(), NOW(), NOW(), NOW(),\n                        NOW(), NOW()\n                    )\n                    ON CONFLICT (task_id) DO UPDATE\n                    SET provider = EXCLUDED.provider,\n                        provider_task_id = EXCLUDED.provider_task_id,\n                        chat_id = COALESCE(EXCLUDED.chat_id, media_delivery_jobs.chat_id),\n                        media_kind = EXCLUDED.media_kind,\n                        request_metadata = EXCLUDED.request_metadata,\n                        status = 'provider_success',\n                        provider_success_at = COALESCE(\n                            media_delivery_jobs.provider_success_at,\n                            NOW()\n                        ),\n                        result_resolved_at = NOW(),\n                        completed_at = NULL,\n                        last_error = NULL,\n                        next_attempt_at = NOW(),\n                        locked_by = NULL,\n                        locked_at = NULL,\n                        updated_at = NOW()\n                    ", task_id, _text(provider, 'unknown')[:32], _text(provider_task_id, str(task_id)), chat_id, media_kind(media_kind), _json(request))
                indexes: list[int] = []
                for index, url in enumerate(urls, start=1):
                    indexes.append(index)
                    await connection.execute("\n                        INSERT INTO media_delivery_items (\n                            task_id, result_index, result_url, resolved_at, updated_at\n                        ) VALUES ($1::UUID, $2::INTEGER, $3::TEXT, NOW(), NOW())\n                        ON CONFLICT (task_id, result_index) DO UPDATE\n                        SET result_url = EXCLUDED.result_url,\n                            url_status = 'available',\n                            download_status = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN 'pending'\n                                ELSE media_delivery_items.download_status\n                            END,\n                            original_status = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN 'pending'\n                                ELSE media_delivery_items.original_status\n                            END,\n                            preview_status = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN 'pending'\n                                ELSE media_delivery_items.preview_status\n                            END,\n                            download_error = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN NULL\n                                ELSE media_delivery_items.download_error\n                            END,\n                            original_error = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN NULL\n                                ELSE media_delivery_items.original_error\n                            END,\n                            preview_error = CASE\n                                WHEN media_delivery_items.result_url <> EXCLUDED.result_url\n                                    THEN NULL\n                                ELSE media_delivery_items.preview_error\n                            END,\n                            resolved_at = NOW(),\n                            updated_at = NOW()\n                        ", task_id, index, url)
                if indexes:
                    await connection.execute('\n                        DELETE FROM media_delivery_items\n                        WHERE task_id = $1::UUID\n                          AND NOT (result_index = ANY($2::INTEGER[]))\n                        ', task_id, indexes)
                else:
                    await connection.execute('DELETE FROM media_delivery_items WHERE task_id=$1::UUID', task_id)
                await connection.execute("\n                    UPDATE media_delivery_jobs\n                    SET status=CASE\n                            WHEN $2::BOOLEAN THEN 'result_resolved'\n                            ELSE 'provider_success'\n                        END,\n                        result_resolved_at=CASE\n                            WHEN $2::BOOLEAN THEN NOW()\n                            ELSE NULL\n                        END,\n                        result_resolution_error=NULL,\n                        attempt_count=CASE WHEN $2::BOOLEAN THEN 0 ELSE attempt_count END,\n                        next_attempt_at=NOW(),\n                        locked_by=NULL,\n                        locked_at=NULL,\n                        updated_at=NOW()\n                    WHERE task_id=$1::UUID\n                    ", task_id, bool(urls))

__all__ = ("MediaDeliveryRepositoryRecordMixin",)
